Allison Memari (3306815)
Suggestions for study in 11s1

Course   Title                 UOC Requirement
-------- -----                ---- -----------
COMP1917 Computing 1             6 Level 1 Core Courses
ENGG1000 Engineering Design      6 Level 1 Core Courses
MATH1081 Discrete Mathematics    6 Level 1 Core Courses
MATH1131 Mathematics 1A          6 Level 1 Core Courses
MATH1141 Higher Mathematics 1    6 Level 1 Core Courses
Free.... Free Electives (many   12 Free elect
