Allison Memari (3306815)
Suggestions for study in 11s2

Course   Title                 UOC Requirement
-------- -----                ---- -----------
COMP1927 Computing 2             6 Level 1 Core Courses
ENGG1000 Engineering Design      6 Level 1 Core Courses
MATH1231 Mathematics 1B          6 Level 1 Core Courses
MATH1241 Higher Mathematics 1    6 Level 1 Core Courses
SENG1031 Software Eng Worksho    6 Level 1 Core Courses
Free.... Free Electives (many    6 Free elect
