Allison Memari (3306815)
Suggestions for study in 12s1

Course   Title                 UOC Requirement
-------- -----                ---- -----------
ENGG1000 Engineering Design      6 Level 1 Core Courses
COMP2041 Software Constructio    6 Level 2 Core Courses
COMP2111 System Modelling and    6 Level 2 Core Courses
COMP2121 Microprocessors & In    6 Level 2 Core Courses
COMP2911 Eng. Design in Compu    6 Level 2 Core Courses
Free.... Free Electives (many    6 Free elect
GenEd... General Education (m    6 GE
